<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Image;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em, Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em, $metadata == null ? new Mapping\ClassMetadata(Image::class) : $metadata);
    }

    public function userImages($userId){

        $db = $this->getEntityManager()->getConnection();
        $qb = $db->createQueryBuilder();

        $qb->select('*')->from('images')->where('user_id = :id')->setParameter('id',$userId);

        return $result = $qb->execute();
    }
}
